# 

In [1]:
import numpy as np

In [2]:
arr = np.arange(50)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [4]:
arr.reshape(2,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [5]:
arr.ravel()    # MAke 2D array into 1D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [6]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [10]:
x = [[1,2,3] , [4,5,6] , [6,7,8]]

In [11]:
ar = np.array(x)

In [12]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [13]:
ar.sum(axis =0)

array([11, 14, 17])

In [15]:
ar.sum(axis=1)

array([ 6, 15, 21])

In [16]:
ar.T   #Transpose finding

array([[1, 4, 6],
       [2, 5, 7],
       [3, 6, 8]])

In [17]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
6
7
8


In [18]:
ar.ndim   # No of dimention finding

2

In [19]:
ar.size

9

In [20]:
ar.nbytes   # Total bytes consumed by array

72

In [21]:
one = np.array([1,2,4,6])

In [22]:
one

array([1, 2, 4, 6])

In [24]:
one.argmax()   # return index of maximum element

np.int64(3)

In [25]:
one.argmin()   # return index of minimum element

np.int64(0)

In [26]:
one.argsort()    # sorted index order

array([0, 1, 2, 3])

In [27]:
arra = [[1,2,3] , [4,5,6] , [6,7,8]]

In [28]:
arra = np.array(arra)

In [29]:
arra

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [30]:
ar.argmax(axis =1)

array([2, 2, 2])

In [31]:
ar.argmin(axis=0)

array([0, 0, 0])

In [32]:
ar + arra   # 2D array sum

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [12, 14, 16]])

In [33]:
ar * arra   # 2D array multiply

array([[ 1,  4,  9],
       [16, 25, 36],
       [36, 49, 64]])

In [52]:
ar - arra

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [53]:
ar / arra

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [34]:
np.sqrt(arra)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.44948974, 2.64575131, 2.82842712]])

In [36]:
arra.max()

np.int64(8)

In [37]:
arra.min()

np.int64(1)

In [38]:
arra.sum()

np.int64(42)

In [39]:
np.where(arra>5)

(array([1, 2, 2, 2]), array([2, 0, 1, 2]))

In [40]:
np.count_nonzero(arra)

9

In [41]:
np.nonzero(arra)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))

In [42]:
import sys

In [43]:
py_arr = [3,2,8,7]


In [44]:
np_arr = np.array(py_arr)

In [45]:
np_arr

array([3, 2, 8, 7])

In [46]:
py_arr

[3, 2, 8, 7]

In [47]:
sys.getsizeof(py_arr)

88

In [49]:
sys.getsizeof(1) * len(py_arr)

112

In [51]:
np_arr.itemsize * np_arr.size    # Numpy allocates less memory than normal python

32