In [1]:
import numpy as np

In [2]:
myArr = np.array([3,6,32,7] , np.int8)

In [3]:
myArr

array([ 3,  6, 32,  7], dtype=int8)

In [4]:
myArr[0]


np.int8(3)

In [5]:
myArr.shape

(4,)

In [6]:
myArr.dtype

dtype('int8')

In [7]:
# Array creating method
listarr = np.array ([[1,2,3] , [4,5,6] , [7,8,9]])


In [8]:
listarr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
listarr.size

9

In [10]:
listarr.shape

(3, 3)

In [11]:
listarr.dtype

dtype('int64')

In [12]:
zeros = np.zeros((2,5))

In [13]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
zeros.dtype

dtype('float64')

In [15]:
rng = np.arange(15)

In [16]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
# 20 equally spaced no generated from 1 to 50 
lspace = np.linspace(1,50,20)


In [18]:
lspace

array([ 1.        ,  3.57894737,  6.15789474,  8.73684211, 11.31578947,
       13.89473684, 16.47368421, 19.05263158, 21.63157895, 24.21052632,
       26.78947368, 29.36842105, 31.94736842, 34.52631579, 37.10526316,
       39.68421053, 42.26315789, 44.84210526, 47.42105263, 50.        ])

In [19]:
emp = np.empty((4,10))

In [20]:
emp

array([[6.95292860e-310, 1.10941035e-311, 9.88131292e-324,
        6.95292860e-310, 2.12199579e-314, 6.95292860e-310,
        2.12199579e-314, 6.95292860e-310, 2.12199579e-314,
        0.00000000e+000],
       [0.00000000e+000, 2.12199579e-311,             nan,
        2.12199579e-314, 4.94065646e-324, 4.94065646e-324,
        0.00000000e+000, 1.10944736e-311, 1.10944718e-311,
        2.12199579e-314],
       [0.00000000e+000, 0.00000000e+000, 4.94065646e-324,
        0.00000000e+000, 1.10941019e-311, 6.95292859e-310,
        0.00000000e+000, 7.41098469e-323, 1.10941019e-311,
        1.10944736e-311],
       [0.00000000e+000, 7.41098469e-323, 4.94065646e-324,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000]])

In [21]:
emplike = np.empty_like(lspace)

In [22]:
emplike

array([ 1.        ,  3.57894737,  6.15789474,  8.73684211, 11.31578947,
       13.89473684, 16.47368421, 19.05263158, 21.63157895, 24.21052632,
       26.78947368, 29.36842105, 31.94736842, 34.52631579, 37.10526316,
       39.68421053, 42.26315789, 44.84210526, 47.42105263, 50.        ])

In [23]:
ide = np.identity(45)


In [24]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(45, 45))

In [25]:
ide.shape

(45, 45)

In [26]:
arr = np.arange(99)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [32]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [33]:
arr = arr.ravel()   #Make 2D array into 1D array