_____
**Write a program to create an array [10, 5, 7, 20, 15, -9, 33], print it, Find the maximum and minimum Value of the array**

In [1]:
#Code here
import numpy as np 

In [2]:
myarr = np.array([10, 5, 7, 20, 15, -9, 33] , np.int8)
print(myarr)
print(np.max(myarr))
print(np.min(myarr))


[10  5  7 20 15 -9 33]
33
-9


______
**Write a program to accept an array of elements and find the maximum without using max function**

In [3]:
#Code here
myarr1 = np.array([10, 5, 7, 20, 15, -9, 33] , np.int8)
maxi = myarr1[0]
for i in range(len(myarr1)):
    if myarr1[i] > maxi:
        maxi = myarr1[i]


In [4]:
print(maxi) 

33


___
**Write a program to accept two matrices [[1,2],[3,4]],   [[2,4],[6,8]]and find the sum and subtraction of two matrices**

In [5]:
#Code here
l1 = np.array ([[1,2],[3,4]])
l2 = np.array ([[2,4],[6,8]])
for i in range (len(l1)):
    for j in range (len(l1[0])):
        print(l1[i][j] + l2[i][j])
    print()


3
6

9
12



___
**Write a program to generate a ranodom matrix of size 5 X 6. Add another row containing random elements to it. Find the sum of each row.**

In [6]:
#Code here
matrix = np.random.rand(5, 6)
print("Original matrix:")
print(matrix)

new_row = np.random.rand(1, 6)

print("New row: ")
print(new_row)

matrix = np.vstack((matrix, new_row))
print("\nMatrix after adding new row:")
print(matrix)

Original matrix:
[[0.10319903 0.4232364  0.17389699 0.63740574 0.25487553 0.58377493]
 [0.40149387 0.06987114 0.05707421 0.39997919 0.527054   0.45303815]
 [0.94418493 0.46866136 0.15509849 0.13732235 0.45235419 0.94350207]
 [0.31808721 0.21360688 0.98781686 0.20893212 0.67478225 0.07421575]
 [0.08564354 0.55664872 0.38887345 0.22774787 0.47967593 0.84063297]]
New row: 
[[0.87227671 0.72308702 0.42861081 0.60449968 0.29107888 0.7973962 ]]

Matrix after adding new row:
[[0.10319903 0.4232364  0.17389699 0.63740574 0.25487553 0.58377493]
 [0.40149387 0.06987114 0.05707421 0.39997919 0.527054   0.45303815]
 [0.94418493 0.46866136 0.15509849 0.13732235 0.45235419 0.94350207]
 [0.31808721 0.21360688 0.98781686 0.20893212 0.67478225 0.07421575]
 [0.08564354 0.55664872 0.38887345 0.22774787 0.47967593 0.84063297]
 [0.87227671 0.72308702 0.42861081 0.60449968 0.29107888 0.7973962 ]]


___
**Write a program to generate a ranodm integer matrix of size 5 X 6. Add another column containing random integers to it. Compute the sine of each element and print it**

In [12]:
#Code here
matrix2 = np.random.rand(5,6)
print(matrix2)

new_col = np.random.rand(5,1)
print(new_col)

matrix2 = np.hstack((matrix2, new_col))
print(matrix2)

[[0.37534281 0.37631891 0.50829261 0.79355229 0.32981679 0.62687677]
 [0.426627   0.1715158  0.54090098 0.14805026 0.39589977 0.2021698 ]
 [0.30470713 0.20983614 0.95597753 0.50028982 0.65939248 0.59028993]
 [0.00622623 0.61816242 0.92992446 0.23377349 0.91342554 0.2033467 ]
 [0.73975455 0.30198177 0.11729469 0.34048962 0.70889159 0.63262642]]
[[0.73489625]
 [0.72533447]
 [0.1308611 ]
 [0.157172  ]
 [0.15109429]]
[[0.37534281 0.37631891 0.50829261 0.79355229 0.32981679 0.62687677
  0.73489625]
 [0.426627   0.1715158  0.54090098 0.14805026 0.39589977 0.2021698
  0.72533447]
 [0.30470713 0.20983614 0.95597753 0.50028982 0.65939248 0.59028993
  0.1308611 ]
 [0.00622623 0.61816242 0.92992446 0.23377349 0.91342554 0.2033467
  0.157172  ]
 [0.73975455 0.30198177 0.11729469 0.34048962 0.70889159 0.63262642
  0.15109429]]


In [13]:
random_matrix = np.random.rand(5,6)
sine_matrix = np.sin(random_matrix)
print("\nSine of each element in the matrix:")
print(sine_matrix)


Sine of each element in the matrix:
[[0.74587121 0.63282628 0.35567651 0.08805375 0.72813554 0.76360313]
 [0.60651247 0.0439972  0.28173447 0.63847353 0.10318854 0.63997249]
 [0.04131887 0.43108127 0.81641349 0.83397028 0.71826614 0.8072783 ]
 [0.35400861 0.67982438 0.46876772 0.57247615 0.19249279 0.51959814]
 [0.79539704 0.82752442 0.20668603 0.03814287 0.27683771 0.38044535]]


___
**Write a program to generate a ranodm matrix of size 5 X 6. Consider the 3rd and 4th row; and 2nd, 3rd and 4th column and print the resultant matrix using slicing**

In [8]:
#Code here
matrix3 = np.random.rand(5,6)
print(matrix3)
sliced_matrix = matrix3[2:4, 1:4]
print("\n")
print(sliced_matrix)



[[0.80958029 0.57083767 0.33593132 0.94703988 0.08662189 0.2829798 ]
 [0.03123139 0.04630021 0.10494855 0.18315765 0.1433367  0.42435524]
 [0.34731259 0.4485885  0.07708844 0.63449834 0.9014962  0.71156138]
 [0.20447394 0.47874917 0.36458707 0.4371901  0.49523076 0.46057417]
 [0.82349544 0.79796599 0.22644404 0.52304928 0.06981275 0.74349307]]


[[0.4485885  0.07708844 0.63449834]
 [0.47874917 0.36458707 0.4371901 ]]


### Great Job!